version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data:cached
    ports:
      - '33061:3306'
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8080:80'
    depends_on:
      - db
    command: uvicorn app.main:api --host "0.0.0.0" --port 80 --reload

