version: '3'
services:
  app:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8080:80'
    command: uvicorn app.main:api --host "0.0.0.0" --port 80 --reload

